### ISSUE TITLE
No chrony role found

### ISSUE THREAD

**Issue by buzzmeister** [federico-razzoli/ansible-mariadb-cluster-example#1]
the meta/main.yml describes a chrony role
e.g.   - { role: chrony }
however the roles folder does not contain the corresponding play, is there a chance you could assist?

**Comment by federico-razzoli** [comment]
@buzzmeister Thank you for a bug report. I probably forgot to add that role to the repository. I'll try to fix the bug this week.

**Comment by federico-razzoli** [comment]
Done.

It uses Ubuntu NTP servers by default, or a single NTP server specified by you. I don't expect it to work with any cloud vendors, but it's easy to modify.
